language: php
php:
    - "7.2"
branches:
    only:
        - master
        - develop
        - "/^(dev-)?feature.*/"
cache:
    directories:
        - "/home/travis/.composer/cache"
before_install:
    - "./bin/composer.phar selfupdate"
install:
    - php -d memory_limit=3G ./bin/composer.phar install -o
script:
    - "./bin/phpcs . --severity=8"
